### ISSUE TITLE
Error running program

### ISSUE THREAD

**Issue by bluemantwo** [nbogojevic/midea-beautiful-air#4] opened 2022-02-12 02:22 UTC
I am trying to run the program, but keep getting an error that I cannot resolve:

pi@hue ~ $ midea-beautiful-air-cli discover --help
Traceback (most recent call last):
  File "/home/pi/.local/bin/midea-beautiful-air-cli", line 6, in <module>
    from midea_beautiful.cli import cli
  File "/home/pi/.local/lib/python3.7/site-packages/midea_beautiful/__init__.py", line 6, in <module>
    from midea_beautiful.cloud import MideaCloud
  File "/home/pi/.local/lib/python3.7/site-packages/midea_beautiful/cloud.py", line 304
    if data := response.get("data", {}):

**Comment by nbogojevic** [comment] 2022-02-12 18:38
Hi @bluemantwo - the problem is with assignement operator that only works on Python 3.8 and later. As 3.8 is the minimum version that the library works on, I've updated the package to v0.8.41 with that restriction. On your side you would need to test it with 3.8 or later Python version. AFAIK installing 3.8 or later on Raspberry PI is not done using `apt install`, you need to rebuild it on pi - there is a script at https://github.com/tvdsluijs/sh-python-installer that can do it.

**Comment by bluemantwo** [comment] 2022-02-13 03:24
Thanks for the fast help!  I was able to install python3.9, but still running into an issue:  

`pi@polyglot:~/.local/bin $ pip3.9 install --upgrade --force-reinstall midea-beautiful-air
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting midea-beautiful-air
  Using cached https://www.piwheels.org/simple/midea-beautiful-air/midea_beautiful_air-0.8.41-py3-none-any.whl (41 kB)
Collecting requests>=2.0
  Using cached https://www.piwheels.org/simple/requests/requests-2.27.1-py2.py3-none-any.whl (63 kB)
Collecting cryptography>=3.0
  Using cached https://www.piwheels.org/simple/cryptography/cryptography-36.0.1-cp39-cp39-linux_armv7l.whl (2.7 MB)
Collecting cffi>=1.12
  Using cached https://www.piwheels.org/simple/cffi/cffi-1.15.0-cp39-cp39-linux_armv7l.whl (369 kB)
Collecting charset-normalizer~=2.0.0
  Using cached https://www.piwheels.org/simple/charset-normalizer/charset_normalizer-2.0.12-py3-none-any.whl (44 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached https://www.piwheels.org/simple/urllib3/urllib3-1.26.8-py2.py3-none-any.whl (155 kB)
Collecting idna<4,>=2.5
  Using cached https://www.piwheels.org/simple/idna/idna-3.3-py3-none-any.whl (64 kB)
Collecting certifi>=2017.4.17
  Using cached https://www.piwheels.org/simple/certifi/certifi-2021.10.8-py2.py3-none-any.whl (151 kB)
Collecting pycparser
  Using cached https://www.piwheels.org/simple/pycparser/pycparser-2.21-py2.py3-none-any.whl (119 kB)
Installing collected packages: certifi, urllib3, pycparser, idna, charset-normalizer, requests, cffi, cryptography, midea-beautiful-air
  Attempting uninstall: certifi
    Found existing installation: certifi 2021.10.8
    Uninstalling certifi-2021.10.8:
      Successfully uninstalled certifi-2021.10.8
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.26.8
    Uninstalling urllib3-1.26.8:
      Successfully uninstalled urllib3-1.26.8
  Attempting uninstall: pycparser
    Found existing installation: pycparser 2.21
    Uninstalling pycparser-2.21:
      Successfully uninstalled pycparser-2.21
  Attempting uninstall: idna
    Found existing installation: idna 3.3
    Uninstalling idna-3.3:
      Successfully uninstalled idna-3.3
  Attempting uninstall: charset-normalizer
    Found existing installation: charset-normalizer 2.0.12
    Uninstalling charset-normalizer-2.0.12:
      Successfully uninstalled charset-normalizer-2.0.12
  Attempting uninstall: requests
    Found existing installation: requests 2.27.1
    Uninstalling requests-2.27.1:
      Successfully uninstalled requests-2.27.1
  Attempting uninstall: cffi
    Found existing installation: cffi 1.15.0
    Uninstalling cffi-1.15.0:
      Successfully uninstalled cffi-1.15.0
  Attempting uninstall: cryptography
    Found existing installation: cryptography 36.0.1
    Uninstalling cryptography-36.0.1:
      Successfully uninstalled cryptography-36.0.1
  Attempting uninstall: midea-beautiful-air
    Found existing installation: midea-beautiful-air 0.8.41
    Uninstalling midea-beautiful-air-0.8.41:
      Successfully uninstalled midea-beautiful-air-0.8.41
Successfully installed certifi-2021.10.8 cffi-1.15.0 charset-normalizer-2.0.12 cryptography-36.0.1 idna-3.3 midea-beautiful-air-0.8.41 pycparser-2.21 requests-2.27.1 urllib3-1.26.8

pi@polyglot:~/.local/bin $ midea-beautiful-air-cli
Traceback (most recent call last):
  File "/home/pi/.local/bin/midea-beautiful-air-cli", line 8, in <module>
    sys.exit(cli())
`

The midea file does correctly list my python3.9 location in the first line, so not sure why still not working.  Again, thanks for the hand holding on this.  I am sure it is not a bug, but rather something I am not doing right.

**Comment by nbogojevic** [comment] 2022-02-13 17:59
Indeed there was regression that was not caught by unit tests. It's fixed now in new v0.8.42.

**Comment by bluemantwo** [comment] 2022-02-13 18:31
Well, we are getting closer!  Still erroring out however.  Sorry to bother you with this, and I really appreciate your sharing your code.

`pi@polyglot:~ $ midea-beautiful-air-cli discover
Traceback (most recent call last):
  File "/home/pi/.local/bin/midea-beautiful-air-cli", line 8, in <module>
    sys.exit(cli())
  File "/home/pi/.local/lib/python3.9/site-packages/midea_beautiful/cli.py", line 296, in cli
    return function(args)
  File "/home/pi/.local/lib/python3.9/site-packages/midea_beautiful/cli.py", line 78, in _run_discover_command
    appliances = find_appliances(
  File "/home/pi/.local/lib/python3.9/site-packages/midea_beautiful/__init__.py", line 85, in find_appliances
    return do_find_appliances(
  File "/home/pi/.local/lib/python3.9/site-packages/midea_beautiful/scanner.py", line 193, in do_find_appliances
    discovery.broadcast(
  File "/home/pi/.local/lib/python3.9/site-packages/midea_beautiful/scanner.py", line 99, in broadcast
    scanned_appliances = list(self._collect_appliances(addresses))
  File "/home/pi/.local/lib/python3.9/site-packages/midea_beautiful/scanner.py", line 55, in _collect_appliances
    appliance = LanDevice(data=data)
  File "/home/pi/.local/lib/python3.9/site-packages/midea_beautiful/lan.py", line 209, in __init__
    self._init_from_data(data)
  File "/home/pi/.local/lib/python3.9/site-packages/midea_beautiful/lan.py", line 252, in _init_from_data
    reply = self._security.aes_decrypt(data[40:-16])
  File "/home/pi/.local/lib/python3.9/site-packages/midea_beautiful/crypto.py", line 338, in aes_decrypt
    decryptor = cipher.decryptor()
  File "/home/pi/.local/lib/python3.9/site-packages/cryptography/hazmat/primitives/ciphers/base.py", line 98, in decryptor
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/home/pi/.local/lib/python3.9/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 6, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/home/pi/.local/lib/python3.9/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 64, in <module>
    from cryptography.hazmat.bindings.openssl import binding
  File "/home/pi/.local/lib/python3.9/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: /usr/lib/arm-linux-gnueabihf/libssl.so.1.1: version `OPENSSL_1_1_1' not found (required by /home/pi/.local/lib/python3.9/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so)
`

**Comment by nbogojevic** [comment] 2022-02-13 23:09
You seem to be using debian 9 (stretch) and openssl doesn't exist in version 1.1.1 for it. You can try to force install cryptography 3.x (https://pypi.org/project/cryptography/#history). Otherwise you may upgrade to debian 10 buster as stretch will be out of LTS by end of June this year (https://wiki.debian.org/LTS).

**Comment by bluemantwo** [comment] 2022-02-14 00:34
That I am sure was it.  I had that one Pi running an old OS for another program.  I will move to a Pi with updated OS.  Thanks again for all the help!

**Closed** 2022-02-15 21:04 UTC
Labels: bug
